### ISSUE TITLE
Minor changes of collections table

### ISSUE THREAD

**Issue by maxbry** [Transkribus/TWI-library#12]
* Fix the height of the thumbnail, so that all rows have the same height
* Keep to the centred view, but enlarge the table a bit
* Instead of Collection Name: “Collection Title”
* Instead of Description, merge the cell with “Collection Title” and call it: “Collection title and description”
** If there is text in the description field, start a new line after the title and add there the text. 
** The last line should have a little button: “Details” – this opens the same page as the “Document Details” button which was introduced to the edit interface!
* Do not show who uploaded the document, but show: Owner: name(s)
* Instead of “Documents”: “No. of Docs” and show the number of documents in the table cell

**Comment by cziaarm** [comment]
- [x] Fix the height of the thumbnail, so that all rows have the same height
- [x] Keep to the centred view, but enlarge the table a bit
- [x] Instead of Collection Name: “Collection Title”
- [x] Instead of Description, merge the cell with “Collection Title” and call it: “Collection title and description”
** If there is text in the description field, start a new line after the title and add there the text.
** The last line should have a little button: “Details” – this opens the same page as the “Document Details” button which was introduced to the edit interface!
- [ ] Do not show who uploaded the document, but show: Owner: name(s)
- [x] Instead of “Documents”: “No. of Docs” and show the number of documents in the table cell

**Comment by cziaarm** [comment]
@maxbry remaining from this are

- Collection Name => Collection Title
- <del>Owners name (but maybe this is being confused by the default description that TranskribusX puts in)</del> pushing back to after Rest service enhancements (ie after Vienna)
