### ISSUE TITLE
Adjust documents table

### ISSUE THREAD

**Issue by maxbry** [Transkribus/TWI-library#13]
* Look and feel of the table should be the same as for the other table
* Size of thumbnails fixed and according to the other table
* Call DocID just ID
* Document title and description according to the other table
* Delete “Author” and “Language” column
* Instead of Pages: “pp.”
* Delete Language column
* Statistics – call it: “Annotation”: show them directly after title/descrition columne. Use simpler text (and conformant with the format for the collection view)
** 10 Lines, 100 words
** Tags: 10 persons, 11 locations, 10 dates
* Add a “Views” colomne:
** Image
** LinebyLine
** SidebySide
** Text
** The links lead you to the dedicated views for p1 of the document. Note: this could also be remembered in the session view

**Comment by cziaarm** [comment]
- [x] Look and feel of the table should be the same as for the other table
- [x] Size of thumbnails fixed and according to the other table
- [ ] <del>Call DocID just ID</del>
- [x] Document title and description according to the other table
- [x] Delete “Author” and “Language” column
- [x] Instead of Pages: “pp.”
- [x] Delete Language column
- [x] Statistics – <del>call it: “Annotation”:</del> show them directly after title/descrition columne. Use simpler text (and conformant with the format for the collection view)
** 10 Lines, 100 words
** Tags: 10 persons, 11 locations, 10 dates
- [x] Add a “Views” colomne:
** Image
** LinebyLine
** SidebySide
** Text
** The links lead you to the dedicated views for p1 of the document. Note: this could also be remembered in the session view

**Comment by cziaarm** [comment]
@maxbry  Had we settled on stats rather than "Annotations" in the end any way? If so this will succeed :)
