### ISSUE TITLE
No empty collections in web interface

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-library#21]
Add parameter to the rest service to get only collections with at least one document.

**Comment by hackmanschorsch** [comment]
@maxbry Please add param 'empty' to the rest call to get only nonempty collections for the table list.
https://transkribus.eu/TrpServer/rest/collections/list?empty=true

**Comment by cziaarm** [comment]
confirmed that this param is correct :)

**Comment by hackmanschorsch** [comment]
Still found some empty collections. empty= true delivers non-empty collections: param name is bullshit (I know :) )

**Comment by maxbry** [comment]
I could add that param [here](https://github.com/Transkribus/TWI-utils/blob/8bf8c58d76cb0901ae702d441c834e26d2e72826/services.py#L271). But once again since the name is pretty useless: If the value is true, does that mean I'm getting empty collections as well or does this mean I'm getting only non-empty collections?
Please please rename that parameter, the name is really bad. If it gives only non-empty collections, my suggestion would be `only_non_empty_collections`. Also, should this setting be default and thus be hardcoded or should the user be able to set a flag somewhere?

**Comment by hackmanschorsch** [comment]
You get only nonempty collections. Since empty collections are useless in the WebUI we can have it as fixed parameter. Use it for the moment as it is - will rename it later on.

**Comment by cziaarm** [comment]
Spooky I could have sworn I added that param already... 

My preference is to add the para to the the calls to t.collections
eg

https://github.com/Transkribus/TWI-library/blob/master/views.py#L45

https://github.com/Transkribus/TWI-library/blob/master/views.py#L59

(oh look I just did it)

I'm not sure why we want to keep the option of  getting empty collections, but I think it is worth keeping the option at least.
