### ISSUE TITLE
Editing interface opens at inconvenient place

### ISSUE THREAD

**Issue by GuenterMuehlberger** [Transkribus/TWI-library#27]
If the first line of a document is at the very right corner than the edit interface is not usable, but the user needs to move the image and the edit interface after having edited the first line.
See attached screenshot
clipboard 1: start window
clipboard 2: first line which looks o.k., but causes the problem! (Indeed it should open at the left side, e.g. 1/5 from the screen)
clipboard 3: the inconvenience becomes obvious when opening the second line
![clipboard01](https://user-images.githubusercontent.com/6583643/34601007-7ee68d78-f1fa-11e7-907b-0921f93bea7f.jpg)
![clipboard02](https://user-images.githubusercontent.com/6583643/34601017-85c8c4f8-f1fa-11e7-9c13-6ea3b6123cc9.jpg)
![clipboard03](https://user-images.githubusercontent.com/6583643/34601020-89d6c9e6-f1fa-11e7-9e5e-c7ed5f8a4241.jpg)

**Comment by GuenterMuehlberger** [comment]
Expected solution: Always place the green point and the edit window at a certain place. e.g. on the left hand side with some intent from the left. 
If the user wants to change and move around the image, then keep it of course.

**Comment by kansallisarkisto** [comment]
I was just about to say that the initially proposed solution only makes things worse. The problem is not caused by the initial placement of the dialog but by the fact that the dialog maintains the same position relative to the previous line (in this case the first one) when switching to another one. Hence placing it 1/5 from the left at first moves the image even more when going to the next one if that switch preserves the relative position. 

The first thing I'd let users test now is to (1) open it 1/5 from the left as you propose and (2) not maintain the relative position horizontally, only vertically. We could then consider having the "preserve the relative position" behaviour activated if and only if the user has moved the dialog around. In that situation it could be a valid assumption that the user prefers a particular offset from the line being edited.

**Comment by kansallisarkisto** [comment]
I have pushed a tiny change which means that the dialog is now placed 1/5 from the left and it doesn't move horizontally when changing to a different line. However, I've preserved the position of the green ball for now because at least to me now that I tested it, it makes a lot more sense to have it close to line being edited. It's easy to change but please test this first. Also: This issue should be in TWI-edit, not TWI-library.

**Comment by kansallisarkisto** [comment]
Now that I understood what behaviour you wanted, I've pushed a change which makes it work as you prefer (I hope!).
